# Generated by Django 4.2.9 on 2024-01-16 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain_stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
