# Generated by Django 4.2.9 on 2024-01-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain_stores', '0003_alter_supplier_supplier_level_alter_supplier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('Завод', 'Zavod'), ('ИП', 'Ip'), ('Розничная сеть', 'Rc')], default='Завод', verbose_name='Тип'),
        ),
    ]
